# Generated by Django 3.1.2 on 2020-10-22 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('shift', models.CharField(choices=[('PM', 'PM'), ('AM', 'AM')], default='AM', max_length=15)),
                ('date', models.DateField(help_text='yyyy-mm-dd')),
                ('age', models.CharField(blank=True, choices=[('ADULT', 'Adult'), ('JUVENILE', 'Juvenile'), (None, ''), ('UNKNOWN', '?')], help_text='Age of squirrel', max_length=20)),
                ('uniquesid', models.CharField(max_length=25)),
                ('Primary_Fur_Color', models.CharField(blank=True, choices=[('Black', 'Black'), ('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), (None, '')], help_text='Fur color', max_length=16)),
                ('Location', models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground'), (None, '')], help_text='Location', max_length=128)),
                ('Specific_Location', models.CharField(blank=True, help_text='Additional notes to the location', max_length=128)),
                ('Running', models.BooleanField(blank=True, help_text='Running', null=True)),
                ('Chasing', models.BooleanField(blank=True, help_text='Chasing', null=True)),
                ('Climbing', models.BooleanField(blank=True, help_text='Climbing', null=True)),
                ('Eating', models.BooleanField(blank=True, help_text='Eating', null=True)),
                ('Foraging', models.BooleanField(blank=True, help_text='Foraging', null=True)),
                ('Other_Activities', models.CharField(blank=True, help_text='Other Activities', max_length=128, null=True)),
                ('Kuks', models.BooleanField(blank=True, help_text='Kuks', null=True)),
                ('Quaas', models.BooleanField(blank=True, help_text='Quaas', null=True)),
                ('Moans', models.BooleanField(blank=True, help_text='Moans', null=True)),
                ('Tail_Flags', models.BooleanField(blank=True, help_text='Tail_Flags', null=True)),
                ('Tail_Twitches', models.BooleanField(blank=True, help_text='Tail_Twitches', null=True)),
                ('Approaches', models.BooleanField(blank=True, help_text='Approaches', null=True)),
                ('Indifferent', models.BooleanField(blank=True, help_text='Indifferent', null=True)),
                ('Runs_From', models.BooleanField(blank=True, help_text='Runs_From', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sightshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sighting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.sighting')),
            ],
        ),
    ]
