# Generated by Django 3.1.2 on 2020-10-22 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sighting',
            old_name='date',
            new_name='Date',
        ),
    ]
