# Generated by Django 3.1.2 on 2020-10-12 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_sightingshowing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sightingshowing',
            new_name='sightshow',
        ),
    ]
