# Generated by Django 3.1.2 on 2020-10-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_sighting_sightid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sighting',
            name='sightid',
        ),
        migrations.AlterField(
            model_name='sighting',
            name='age',
            field=models.CharField(help_text='Age of squirrel', max_length=100),
        ),
    ]
