# Generated by Django 3.1.2 on 2020-10-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20201015_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='age',
            field=models.CharField(choices=[('ADULT', 'Adult'), ('JUVENILE', 'Juvenile'), ('UNKNOWN', '?')], default='ADULT', help_text='Age of squirrel', max_length=20),
        ),
    ]
