# Generated by Django 3.1.2 on 2020-10-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20201016_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='date',
            field=models.CharField(default='mmddyyyy', max_length=16),
        ),
    ]
