# Generated by Django 3.1.2 on 2020-10-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_auto_20201018_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='latitude',
            field=models.DecimalField(decimal_places=13, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='longitude',
            field=models.DecimalField(decimal_places=13, max_digits=14, null=True),
        ),
    ]
