# Generated by Django 3.1.2 on 2020-10-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_auto_20201018_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
