# Generated by Django 3.1.2 on 2020-10-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_auto_20201018_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='uniquesid',
            field=models.CharField(default='DL-SF-DDDD-DD', max_length=20),
        ),
    ]
