# Generated by Django 3.1.2 on 2020-10-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_auto_20201018_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='Approaches',
            field=models.NullBooleanField(help_text='Approaches'),
        ),
        migrations.AddField(
            model_name='sighting',
            name='Chasing',
            field=models.NullBooleanField(help_text='Chasing'),
        ),
        migrations.AddField(
            model_name='sighting',
            name='Climbing',
            field=models.NullBooleanField(help_text='Climbing'),
        ),
        migrations.AddField(
            model_name='sighting',
            name='Eating',
            field=models.NullBooleanField(help_text='Eating'),
        ),
        migrations.AddField(
            model_name='sighting',
            name='Foraging',
            field=models.NullBooleanField(help_text='Foraging'),
        ),
        migrations.AddField(
            model_name='sighting',
            name='Indifferent',
            field=models.NullBooleanField(help_text='Indifferent'),
        ),
        migrations.AddField(
            model_name='sighting',
            name='Kuks',
            field=models.NullBooleanField(help_text='Kuks'),
        ),
        migrations.AddField(
            model_name='sighting',
            name='Location',
            field=models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground'), (None, '')], help_text='Location', max_length=128),
        ),
        migrations.AddField(
            model_name='sighting',
            name='Moans',
            field=models.NullBooleanField(help_text='Moans'),
        ),
        migrations.AddField(
            model_name='sighting',
            name='Other_Activities',
            field=models.CharField(blank=True, help_text='Other Activities', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='Primary_Fur_Color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), (None, '')], help_text='Fur color', max_length=16),
        ),
        migrations.AddField(
            model_name='sighting',
            name='Quaas',
            field=models.NullBooleanField(help_text='Quaas'),
        ),
        migrations.AddField(
            model_name='sighting',
            name='Running',
            field=models.NullBooleanField(help_text='Running'),
        ),
        migrations.AddField(
            model_name='sighting',
            name='Runs_From',
            field=models.NullBooleanField(help_text='Runs_From'),
        ),
        migrations.AddField(
            model_name='sighting',
            name='Specific_Location',
            field=models.CharField(blank=True, help_text='Additional notes to the location', max_length=128),
        ),
        migrations.AddField(
            model_name='sighting',
            name='Tail_Flags',
            field=models.NullBooleanField(help_text='Tail_Flags'),
        ),
        migrations.AddField(
            model_name='sighting',
            name='Tail_Twitches',
            field=models.NullBooleanField(help_text='Tail_Twitches'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='age',
            field=models.CharField(blank=True, choices=[('ADULT', 'Adult'), ('JUVENILE', 'Juvenile'), (None, ''), ('UNKNOWN', '?')], help_text='Age of squirrel', max_length=20),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='date',
            field=models.DateField(blank=True, default='mmddyyyy', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='uniquesid',
            field=models.CharField(default='DL-SF-DDDD-DD', max_length=25),
        ),
    ]
